# Generated by Django 2.1.3 on 2018-12-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='description',
            new_name='body',
        ),
    ]
