# Generated by Django 2.1.3 on 2018-12-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='currenteducation',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currenteducation',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
