# Generated by Django 2.2.3 on 2019-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0002_auto_20190604_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currenteducation',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='previouseducation',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
