# Generated by Django 2.2.3 on 2019-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0004_auto_20190830_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
