# Generated by Django 2.1.3 on 2018-12-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0004_auto_20181208_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='student',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
