# Generated by Django 2.2.6 on 2019-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0006_auto_20191216_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.SlugField(blank=True, default=None, max_length=31, null=True, unique=True),
        ),
    ]
