# Generated by Django 2.2.6 on 2020-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0007_auto_20191216_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouseducation',
            name='graduation',
            field=models.CharField(choices=[('mat', 'Matriculate (Class X)'), ('int', 'Intermediate (Class XII)'), ('ass', 'Associate'), ('gra', 'Graduate (UG)'), ('pos', 'Postgraduate (PG)'), ('doc', 'Doctorate (PhD)'), ('pdo', 'Postdoctorate (Postdoc)')], max_length=3),
        ),
    ]
