# Generated by Django 3.0.3 on 2020-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0008_auto_20200124_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouseducation',
            name='graduation',
            field=models.CharField(choices=[('mat', 'Matriculate (Class X)'), ('int', 'Intermediate (Class XII)'), ('dip', 'Diploma'), ('ass', 'Associate'), ('gra', 'Graduate (UG)'), ('pos', 'Postgraduate (PG)'), ('doc', 'Doctorate (PhD)'), ('pdo', 'Postdoctorate (Postdoc)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
