# Generated by Django 3.0.3 on 2020-12-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0009_auto_20200918_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_cgpa',
            field=models.BooleanField(default=True),
        ),
    ]
