# Generated by Django 3.2.8 on 2022-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_biodata', '0010_profile_show_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_cgpa',
            field=models.BooleanField(default=False),
        ),
    ]
